GET http://localhost:5000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhY29zNHBhY29zQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMjNvNCIsImlhdCI6MTY5NjEwNzEyNSwiZXhwIjoxNjk2MTA3NzI1fQ.BIqnbehM14jtAtE2obOLwpy2lnCSOYJ9qdsCfLe0c7I

### 

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "tacos4pacos@gmail.com", 
    "password": "23o4"
}

###

POST http://localhost:5000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhY29zNHBhY29zQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMjNvNCIsImlhdCI6MTY5NjEwNzMyMX0.H_qyPmmwNAtf1mnknOdMFH6eN9FE9gqPMpp64id-KDo"
}


