GET http://localhost:5000/users 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhY29zNHBhY29zQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMjNvNCIsImlhdCI6MTY5NjEwOTMxNSwiZXhwIjoxNjk2MTA5MzQ1fQ.4-zRf6o0-0EK_S8CDmG4MtXCvrniYQh-Sd3Jxp51PF4

### 

POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "tacos4pacos@gmail.com", 
    "password": "23o4"
}

###

POST http://localhost:5000/token 
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhY29zNHBhY29zQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMjNvNCIsImlhdCI6MTY5NjEwOTU4M30.k7qopw_C963qLdZlWXKE6AtubpLw6lI19q5XiIQ-fe0"
}

###

DELETE http://localhost:5000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhY29zNHBhY29zQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMjNvNCIsImlhdCI6MTY5NjEwOTU4M30.k7qopw_C963qLdZlWXKE6AtubpLw6lI19q5XiIQ-fe0"
}


### 
POST https://accounts.spotify.com/api/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=d49a1766a47d406f8e827bf35bdc6865&client_secret=d10ecf5d51864e58a517facda974f845

###
GET https://api.spotify.com/v1/search?q=codeine%20crazy&type=track&market=US&limit=3
Content-type: application/json
Authorization: Bearer BQDln1hgYVub5XcUaeB57-VzjjIz8-7dujmKQ647oyeLvDm_S_ohT3ghiPEkU6c-KCzW6EiJSt1LTfs1Be8nRAjKAR5-EJFqLQ4p7DoxoGOT76uQ2kk


###

Get https://api.spotify.com/v1/tracks/0joQFwiBKmi6X1Iq5R1ubH
Content-type: application/json
Authorization: Bearer BQDln1hgYVub5XcUaeB57-VzjjIz8-7dujmKQ647oyeLvDm_S_ohT3ghiPEkU6c-KCzW6EiJSt1LTfs1Be8nRAjKAR5-EJFqLQ4p7DoxoGOT76uQ2kk


